services:
  server:
    image: ghcr.io/nazarkurii/marshrutka_api:latest
    restart: unless-stopped
    env_file:
      - ./server/.env
    networks:
      - marshrutka_net

  customer-ui:
    image: ghcr.io/nazarkurii/marshrutka-customer-ui:latest
    restart: unless-stopped
    networks:
      - marshrutka_net

  nginx:
    image: nginx:1.29.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
      - customer-ui
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
     - ./certbot/www:/var/www/certbot
     - ./certbot/conf:/etc/letsencrypt:ro
    networks:
      - marshrutka_net
    
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c
    command: >
      certonly --webroot -w /var/www/certbot
      --force-renewal 
      --email nazar.nazar.kurii@gmail.com 
      --agree-tos
      -d marshrutka.store 
      -d pumpkinbooks.store
    networks:
      - marshrutka_net

networks:
  marshrutka_net:
    driver: bridge
