version: '3.9'

services:
  server:
    image: marshrutka/server:latest
    restart: unless-stopped
    env_file:
      - ./server/.env
    networks:
      - marshrutka_net

  customer-ui:
    image: marshrutka/customer-ui:latest
    restart: unless-stopped
    networks:
      - marshrutka_net

  nginx:
    image: marshrutka/nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
      - customer-ui
    networks:
      - marshrutka_net

# Define a single network
networks:
  marshrutka_net:
    driver: bridge
